CSECT Symbol  Value   Length  Flags:
--------------------------------------
COPY		00000	01076	R
	FIRST	00000		R
	CLOOP	00006		R
	ENDFIL	0001A		R
	EOF	0002D		R
	RETADR	00030		R
	LENGTH	00033		R
	BUFFER	00036		R
	RDREC	01036		R
	RLOOP	01040		R
	EXIT	01056		R
	INPUT	0105C		R
	WRREC	0105D		R
	WLOOP	01062		R
	OUTPUT	01076		R

Literal Table
Name	Operand	Address	Length
--------------------------------------
